#!/bin/bash
formulas=($(brew update | sed -En '/==> (Updated|New)/,/==> Deleted/{/==>/d;p;}' | sort | uniq))
current=1

usage() {
	echo '[i] - show info; [s] - skip; [h] - visit homepage and continue'
}

usage

for formula in "${formulas[@]}"; do
	printf "[ %3s / %3s ] %s\n" $current ${#formulas[@]} $formula
	current=$((current+1))

	while read -rsn1 c
	do
		case $c in
			i) brew info $formula;;
			h) brew home $formula; break;;
			s) break;;
			*) usage;;
		esac
	done
done
